version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SlackWhatsNew01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jsh0fwgghf1s"
s3_prefix = "SlackWhatsNew01"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SlackBotUrl=\"slack.bot.url.prod\""
image_repositories = []
